import { createContext, useState } from "react"


const createContextProvider=createContext();
export const Provider=({children})=>
{
    const [open1,setOpen1]=useState(false);
    const suggesting=()=>
    {
        setOpen1(def=>!def);
    }
    const generalArrayNames = [
        {"num": 1, "name": "abdominal pain"},
        {"num": 2, "name": "abnormal menstruation"},
        {"num": 3, "name": "acidity"},
        {"num": 4, "name": "acute liver failure"},
        {"num": 5, "name": "altered sensorium"},
        {"num": 6, "name": "anxiety"},
        {"num": 7, "name": "back pain"},
        {"num": 8, "name": "belly pain"},
        {"num": 9, "name": "blackheads"},
        {"num": 10, "name": "bladder discomfort"},
        {"num": 11, "name": "blister"},
        {"num": 12, "name": "blood in sputum"},
        {"num": 13, "name": "bloody stool"},
        {"num": 14, "name": "blurred and distorted vision"},
        {"num": 15, "name": "breathlessness"},
        {"num": 16, "name": "brittle nails"},
        {"num": 17, "name": "bruising"},
        {"num": 18, "name": "burning micturition"},
        {"num": 19, "name": "chest pain"},
        {"num": 20, "name": "chills"},
        {"num": 21, "name": "cold hands and feets"},
        {"num": 22, "name": "coma"},
        {"num": 23, "name": "constipation"},
        {"num": 24, "name": "continuous feel of urine"},
        {"num": 25, "name": "continuous sneezing"},
        {"num": 26, "name": "cough"},
        {"num": 27, "name": "cramps"},
        {"num": 28, "name": "dark urine"},
        {"num": 29, "name": "dehydration"},
        {"num": 30, "name": "depression"},
        {"num": 31, "name": "diarrhoea"},
        {"num": 32, "name": "dischromic patches"},
        {"num": 33, "name": "distention of abdomen"},
        {"num": 34, "name": "dizziness"},
        {"num": 35, "name": "drying and tingling lips"},
        {"num": 36, "name": "enlarged thyroid"},
        {"num": 37, "name": "excessive hunger"},
        {"num": 38, "name": "extra marital contacts"},
        {"num": 39, "name": "family history"},
        {"num": 40, "name": "fast heart rate"},
        {"num": 41, "name": "fatigue"},
        {"num": 42, "name": "fluid overload"},
        {"num": 43, "name": "foul smell of urine"},
        {"num": 44, "name": "headache"},
        {"num": 45, "name": "high fever"},
        {"num": 46, "name": "hip joint pain"},
        {"num": 47, "name": "history of alcohol consumption"},
        {"num": 48, "name": "increased appetite"},
        {"num": 49, "name": "indigestion"},
        {"num": 50, "name": "inflammatory nails"},
        {"num": 51, "name": "internal itching"},
        {"num": 52, "name": "irregular sugar level"},
        {"num": 53, "name": "irritability"},
        {"num": 54, "name": "irritation in anus"},
        {"num": 55, "name": "itching"},
        {"num": 56, "name": "joint pain"},
        {"num": 57, "name": "knee pain"},
        {"num": 58, "name": "lack of concentration"},
        {"num": 59, "name": "lethargy"},
        {"num": 60, "name": "loss of appetite"},
        {"num": 61, "name": "loss of balance"},
        {"num": 62, "name": "loss of smell"},
        {"num": 63, "name": "malaise"},
        {"num": 64, "name": "mild fever"},
        {"num": 65, "name": "mood swings"},
        {"num": 66, "name": "movement stiffness"},
        {"num": 67, "name": "mucoid sputum"},
        {"num": 68, "name": "muscle pain"},
        {"num": 69, "name": "muscle wasting"},
        {"num": 70, "name": "muscle weakness"},
        {"num": 71, "name": "nausea"},
        {"num": 72, "name": "neck pain"},
        {"num": 73, "name": "nodal skin eruptions"},
        {"num": 74, "name": "obesity"},
        {"num": 75, "name": "pain behind the eyes"},
        {"num": 76, "name": "pain during bowel movements"},
        {"num": 77, "name": "pain in anal region"},
        {"num": 78, "name": "painful walking"},
        {"num": 79, "name": "palpitations"},
        {"num": 80, "name": "passage of gases"},
        {"num": 81, "name": "patches in throat"},
        {"num": 82, "name": "phlegm"},
        {"num": 83, "name": "polyuria"},
        {"num": 84, "name": "prominent veins on calf"},
        {"num": 85, "name": "puffy face and eyes"},
        {"num": 86, "name": "pus filled pimples"},
        {"num": 87, "name": "receiving blood transfusion"},
        {"num": 88, "name": "receiving unsterile injections"},
        {"num": 89, "name": "red sore around nose"},
        {"num": 90, "name": "red spots over body"},
        {"num": 91, "name": "redness of eyes"},
        {"num": 92, "name": "restlessness"},
        {"num": 93, "name": "runny nose"},
        {"num": 94, "name": "rusty sputum"},
        {"num": 95, "name": "scurring"},
        {"num": 96, "name": "shivering"},
        {"num": 97, "name": "silver like dusting"},
        {"num": 98, "name": "sinus pressure"},
        {"num": 99, "name": "skin peeling"},
        {"num": 100, "name": "skin rash"},
        {"num": 101, "name": "slurred speech"},
        {"num": 102, "name": "small dents in nails"},
        {"num": 103, "name": "spinning movements"},
        {"num": 104, "name": "spotting urination"},
        {"num": 105, "name": "stomach bleeding"},
        {"num": 106, "name": "stomach pain"},
        {"num": 107, "name": "sunken eyes"},
        {"num": 108, "name": "sweating"},
        {"num": 109, "name": "swelled lymph nodes"},
        {"num": 110, "name": "swelling joints"},
        {"num": 111, "name": "swelling of stomach"},
        {"num": 112, "name": "swollen blood vessels"},
        {"num": 113, "name": "swollen extremeties"},
        {"num": 114, "name": "swollen legs"},
        {"num": 115, "name": "throat irritation"},
        {"num": 116, "name": "toxic look (typhos)"},
        {"num": 117, "name": "ulcers on tongue"},
        {"num": 118, "name": "unsteadiness"},
        {"num": 119, "name": "visual disturbances"},
        {"num": 120, "name": "vomiting"},
        {"num": 121, "name": "watering from eyes"},
        {"num": 122, "name": "weakness in limbs"},
        {"num": 123, "name": "weakness of one body side"},
        {"num": 124, "name": "weight gain"},
        {"num": 125, "name": "weight loss"},
        {"num": 126, "name": "yellow crust ooze"},
        {"num": 127, "name": "yellow urine"},
        {"num": 128, "name": "yellowing of eyes"},
        {"num": 129, "name": "yellowish skin"}
    ];

    const [data,setData]=useState([]);


    const [theme,setTheme]=useState(true)
    return(
        <createContextProvider.Provider value={{suggesting,open1,theme,setTheme,generalArrayNames,data,setData}}>
            {children}
        </createContextProvider.Provider>
    )
}
export default createContextProvider;
